export const users = [
  {
    id: 0,
    name: "Aly Abd-Elhady",
    email: "aly.abdelhady@example.com",
    image: "https://randomuser.me/api/portraits/men/79.jpg",
    points: "4530",
    subscription: "March 23, 2019",
    login: "March 23, 2022",
  },
  {
    id: 1,
    name: "Svetlana Bothe",
    email: "svetlana.bothe@example.com",
    image: "https://randomuser.me/api/portraits/women/85.jpg",
    points: "4530",
    subscription: "March 23, 2019",
    login: "March 23, 2022",
  },
  {
    id: 2,
    name: "Clifford Thomas",
    email: "clifford.thomas@example.com",
    image: "https://randomuser.me/api/portraits/men/54.jpg",
    points: "4530",
    subscription: "March 23, 2019",
    login: "March 23, 2022",
  },
  {
    id: 3,
    name: "Kübra Erçetin",
    email: "aly.abdelhady@gmail.com",
    image: "https://randomuser.me/api/portraits/women/7.jpg",
    points: "4530",
    subscription: "March 23, 2019",
    login: "March 23, 2022",
  },
  {
    id: 4,
    name: "Licélia Ribeiro",
    email: "licelia.ribeiro@example.com",
    image: "https://randomuser.me/api/portraits/women/24.jpg",
    points: "4530",
    subscription: "March 23, 2019",
    login: "March 23, 2022",
  },
  {
    id: 5,
    name: "Scarlett Howard",
    email: "scarlett.howard@example.com",
    image: "https://randomuser.me/api/portraits/women/51.jpg",
    points: "4530",
    subscription: "March 23, 2019",
    login: "March 23, 2022",
  },
  {
    id: 6,
    name: "Janusz Thoma",
    email: "janusz.thoma@example.com",
    image: "https://randomuser.me/api/portraits/men/78.jpg",
    points: "4530",
    subscription: "March 23, 2019",
    login: "March 23, 2022",
  },
  {
    id: 7,
    name: "Lillian Dunn",
    email: "lillian.dunn@example.com",
    image: "https://randomuser.me/api/portraits/women/27.jpg",
    points: "4530",
    subscription: "March 23, 2019",
    login: "March 23, 2022",
  },
  {
    id: 8,
    name: "Kerim Eronat",
    email: "kerim.eronat@example.com",
    image: "https://randomuser.me/api/portraits/men/25.jpg",
    points: "4530",
    subscription: "March 23, 2019",
    login: "March 23, 2022",
  },
  {
    id: 9,
    name: "Natalie Frazier",
    email: "natalie.frazier@example.com",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
    points: "4530",
    subscription: "March 23, 2019",
    login: "March 23, 2022",
  },
];
